[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
flink = "D3qpVSKG3Qn7QdkbrzSDwKeWsKgqDjJEFHkShgdSCoWN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/u2135/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
